name: Bug Report
description: Report a bug or unexpected behavior in the analysis scripts
title: "[Bug]: "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please provide detailed information to help us reproduce and fix the issue.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the analysis is affected?
      options:
        - Data Processing (computations)
        - Visualization (figures)
        - Configuration
        - Documentation
        - Installation/Setup
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With data '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Message
      description: Complete error message and traceback if applicable
      render: shell

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Output of `python --version`
      placeholder: "Python 3.12.1"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Output of `pip list` or relevant package versions
      render: text

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information (data characteristics, system specs, etc.)
